In [1]:
import numpy as np

### np.abs or np.absolute

### np.add (concept of broadcasting)

Add arguments element-wise.

In [2]:
x1 = np.arange(9.0).reshape((3, 3))
x2 = np.arange(3.0)
np.add(x1, x2)

array([[ 0.,  2.,  4.],
       [ 3.,  5.,  7.],
       [ 6.,  8., 10.]])

### np.all?

Test whether all array elements along a given axis evaluate to True.

In [3]:
np.all([-1, 4, 5])

True

In [4]:
np.all([-1, 0, 5])

False

In [5]:
np.all([[True,False],[True,True]], axis=0)

array([ True, False])

### np.amax or np.max

Return the maximum of an array or maximum along an axis.

In [6]:
np.amax?

In [7]:
x=np.array([[0, 1],[2, 3]])

In [8]:
np.amax(x)

3

In [9]:
np.amax(x,axis=0)

array([2, 3])

In [10]:
np.amax(x,axis=1)

array([1, 3])

### np.amin or np.min

### np.angle

Return the angle of the complex argument.

In [11]:
np.angle([1.0, 1.0j, 1+1j]) 

array([0.        , 1.57079633, 0.78539816])

### np.append

Append values to the end of an array.

In [12]:
np.append([1, 2, 3], [[4, 5, 6], [7, 8, 9]])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
x=np.append([[1, 2, 3], [4, 5, 6]], [[7, 8, 9]], axis=0)

### np.arange

### np.argmax

Returns the indices of the maximum values along an axis.

In [14]:
a = np.arange(6).reshape(2,3)
a[1][1]=100
a

array([[  0,   1,   2],
       [  3, 100,   5]])

In [15]:
np.argmax(a)

4

In [16]:
np.argmax(a, axis=0)

array([1, 1, 1])

In [17]:
np.argmax(a, axis=1)

array([2, 1])

### np.argmin

In [18]:
np.argsort?

Returns the indices that would sort an array.

In [19]:
x = np.array([3, 1, 2])
np.argsort(x)

array([1, 2, 0])

In [20]:
x = np.array([[0, 3], [2, 2]])
np.argsort(x, axis=0)

array([[0, 1],
       [1, 0]])

In [21]:
np.argsort(x, axis=1)

array([[0, 1],
       [0, 1]])

### np.argwhere

Find the indices of array elements that are non-zero, grouped by element

In [22]:
x = np.arange(6).reshape(2,3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [23]:
np.argwhere(x>1)

array([[0, 2],
       [1, 0],
       [1, 1],
       [1, 2]])

### np.around

In [24]:
np.around([0.37, 1.64])

array([0., 2.])

In [25]:
np.around([0.37, 1.64], decimals=1)

array([0.4, 1.6])

### np.array

Create an array

In [26]:
np.array([1, 2, 3], ndmin=2)

array([[1, 2, 3]])

In [27]:
np.array([1, 2, 3], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [28]:
np.array_equal?

True if two arrays have the same shape and elements, False otherwise

In [29]:
np.array_equal([1, 2], [1, 2])

True

In [30]:
np.array_equal([1, 2], [1, 2, 3])

False

### np.array_split

Split an array into multiple sub-arrays

In [31]:
x = np.arange(8.0)
np.array_split(x, 3)

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7.])]

In [32]:
x = np.arange(9)
np.array_split(x, 4)

[array([0, 1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]

### np.average

Compute the weighted average along the specified axis

In [33]:
data = np.arange(1, 5)
data

array([1, 2, 3, 4])

In [34]:
np.average(data)

2.5

In [35]:
data = np.arange(6).reshape((3, 2))
data

array([[0, 1],
       [2, 3],
       [4, 5]])

In [36]:
np.average(data, axis=1, weights=[1./4, 3./4])

array([0.75, 2.75, 4.75])

In [37]:
np.bincount?

Count number of occurrences of each value in array of non-negative ints

In [38]:
 np.bincount(np.arange(5))

array([1, 1, 1, 1, 1])

In [39]:
np.bincount(np.array([0, 1, 1, 3, 2, 1, 7]))

array([1, 3, 1, 1, 0, 0, 0, 1])

### np.ceil

Return the ceiling of the input, element-wise

In [40]:
a = np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2.0])
a

array([-1.7, -1.5, -0.2,  0.2,  1.5,  1.7,  2. ])

In [41]:
np.ceil(a)

array([-1., -1., -0.,  1.,  2.,  2.,  2.])

## np.compress

Return selected slices of an array along given axis.

In [42]:
a = np.array([[1, 2], [3, 4], [5, 6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [43]:
np.compress([0,0, 1], a, axis=0)

array([[5, 6]])

In [44]:
np.compress([False, True, True], a, axis=0)

array([[3, 4],
       [5, 6]])

In [45]:
np.compress([False, True], a, axis=1)

array([[2],
       [4],
       [6]])

### np.concatenate

Join a sequence of arrays along an existing axis

In [46]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

In [47]:
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [48]:
np.concatenate((a, b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [49]:
np.concatenate((a, b), axis=None)

array([1, 2, 3, 4, 5, 6])

### np.conj

Return the complex conjugate, element-wise

In [50]:
np.conjugate(1+2j)

(1-2j)

### np.convolve

Returns the discrete, linear convolution of two one-dimensional sequences

In [51]:
np.convolve([1, 2, 3], [1,0,0])

array([1, 2, 3, 0, 0])

### np.copy

In [52]:
x = np.array([1, 2, 3])
y = x # reference y
z = np.copy(x)  # copy z

### np.corrcoef

### np.count_nonzero

Counts the number of non-zero values in the array

In [53]:
np.count_nonzero(np.eye(4))

4

In [54]:
a = np.array([[0, 1, 7, 0],[3, 0, 2, 19]])
np.count_nonzero(a)

5

### np.deg2rad

Convert angles from degrees to radians

### np.delete

Return a new array with sub-arrays along an axis deleted

In [55]:
arr=np.array([10,20,30,40,50])
arr

array([10, 20, 30, 40, 50])

In [56]:
np.delete(arr, 2)

array([10, 20, 40, 50])

In [57]:
np.delete(arr, (1,2))

array([10, 40, 50])

In [58]:
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [59]:
np.delete(arr, 1, axis=0) 

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [60]:
np.delete(arr, 0, axis=1) 

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])

### np.diag

Extract a diagonal or construct a diagonal array

In [61]:
x = np.arange(9).reshape((3,3))
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [62]:
np.diag(x)

array([0, 4, 8])

In [63]:
np.diag(x, k=1)

array([1, 5])

In [64]:
np.diag(x, k=-1)

array([3, 7])

### np.diag_indices

Return the indices to access the main diagonal of an arra

In [65]:
di = np.diag_indices(3)
di

(array([0, 1, 2]), array([0, 1, 2]))

In [66]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [67]:
a[di] = 100
a

array([[100,   1,   2],
       [  3, 100,   5],
       [  6,   7, 100]])

### np.dot

Dot product of two arrays

In [68]:
a = [[1, 0], [0, 1]]
b = [[4, 1], [2, 2]]

In [69]:
np.dot(a, b)

array([[4, 1],
       [2, 2]])

### np.empty

Return a new array of given shape and type, without initializing entries

In [70]:
np.empty([2, 2])

array([[2.e-323, 5.e-324],
       [1.e-323, 1.e-323]])

### np.equal

Return (x1 == x2) element-wise

In [71]:
np.equal([0, 1, 3], np.arange(3))

array([ True,  True, False])

In [72]:
a = np.array([2, 4, 6])
b = np.array([2, 4, 2])
a == b

array([ True,  True, False])

### np.empty_like

Return a new array with the same shape and type as a given array

In [73]:
a = ([1,2,3], [4,5,6])  
np.empty_like(a)

array([[-2305843009213693952, -8070441753733644015,                    3],
       [                   0,                    0,      844424930131968]])

### np.expand_dims

Expand the shape of an array. Insert a new axis that will appear at the `axis` position in the expanded array shape.

In [74]:
x = np.array([1, 2])
x.ndim

1

In [75]:
y = np.expand_dims(x, axis=0)
y

array([[1, 2]])

In [76]:
y.ndim

2

In [77]:
y = np.expand_dims(x, axis=1)
y

array([[1],
       [2]])

In [78]:
y.ndim

2

### np.extract

Return the elements of an array that satisfy some condition

In [79]:
arr = np.arange(12).reshape((3, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [80]:
condition = np.mod(arr, 3)==0
condition

array([[ True, False, False,  True],
       [False, False,  True, False],
       [False,  True, False, False]])

In [81]:
np.extract(condition, arr)

array([0, 3, 6, 9])

In [82]:
np.eye?

Return a 2-D array with ones on the diagonal and zeros elsewhere

In [83]:
np.eye(2, dtype=int)

array([[1, 0],
       [0, 1]])

In [84]:
np.eye(3, k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

### np.fill_diagonal

Fill the main diagonal of the given array of any dimensionality

In [93]:
a = np.zeros((3, 3), int)
a

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [95]:
np.fill_diagonal(a, 5)
a

array([[5, 0, 0],
       [0, 5, 0],
       [0, 0, 5]])

In [97]:
a = np.zeros((5, 3), int)
a

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [98]:
np.fill_diagonal(a, 4)
a

array([[4, 0, 0],
       [0, 4, 0],
       [0, 0, 4],
       [0, 0, 0],
       [0, 0, 0]])

### np.flip

Reverse the order of elements in an array along the given axis

In [103]:
a=np.array([1,2,3,4,5])
np.flip(a)

array([5, 4, 3, 2, 1])

In [105]:
A = np.arange(8).reshape((2,2,2))

In [106]:
np.flip(A, 0)

array([[[4, 5],
        [6, 7]],

       [[0, 1],
        [2, 3]]])

In [107]:
np.flip(A, 1)

array([[[2, 3],
        [0, 1]],

       [[6, 7],
        [4, 5]]])

### np.fliplr

Reverse the order of elements along axis 1 (left/right)

In [109]:
A = np.diag([1.,2.,3.])
A

array([[1., 0., 0.],
       [0., 2., 0.],
       [0., 0., 3.]])

In [110]:
np.fliplr(A)

array([[0., 0., 1.],
       [0., 2., 0.],
       [3., 0., 0.]])

### np.floor

Return the floor of the input, element-wise

In [112]:
a = np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2.0])
np.floor(a)

array([-2., -2., -1.,  0.,  1.,  1.,  2.])

### np.full

Return a new array of given shape and type, filled with `fill_value`

In [115]:
np.full((2, 2), np.inf)

array([[inf, inf],
       [inf, inf]])

In [116]:
np.full((2, 2), 10)

array([[10, 10],
       [10, 10]])

In [117]:
np.full((2, 2), [1, 2])

array([[1, 2],
       [1, 2]])

In [118]:
np.full_like?

Return a full array with the same shape and type as a given array

In [119]:
x = np.arange(6, dtype=int)

In [120]:
np.full_like(x, 1)

array([1, 1, 1, 1, 1, 1])

In [122]:
y = np.zeros([2, 2, 3], dtype=int)

In [123]:
np.full_like(y, [0, 0, 255])

array([[[  0,   0, 255],
        [  0,   0, 255]],

       [[  0,   0, 255],
        [  0,   0, 255]]])